// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnWaueIWXMgJ5iAx8AEiFTh1kSg3jiFpk',
    appId: '1:859425192019:web:b36f083d9bdd53e801eea6',
    messagingSenderId: '859425192019',
    projectId: 'parkingapp-c2aed',
    authDomain: 'parkingapp-c2aed.firebaseapp.com',
    storageBucket: 'parkingapp-c2aed.firebasestorage.app',
    measurementId: 'G-9XWYTDQ7D4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs3jcGDsPndSNmUvGqleX3_XuLKJSjxUg',
    appId: '1:859425192019:android:c2ecaa652f7f2f7301eea6',
    messagingSenderId: '859425192019',
    projectId: 'parkingapp-c2aed',
    storageBucket: 'parkingapp-c2aed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1BBGKb3737F6OVO3scZtQVXG7Mf2LUrc',
    appId: '1:859425192019:ios:8942bd37d627c6b501eea6',
    messagingSenderId: '859425192019',
    projectId: 'parkingapp-c2aed',
    storageBucket: 'parkingapp-c2aed.firebasestorage.app',
    iosBundleId: 'com.example.parkingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1BBGKb3737F6OVO3scZtQVXG7Mf2LUrc',
    appId: '1:859425192019:ios:8942bd37d627c6b501eea6',
    messagingSenderId: '859425192019',
    projectId: 'parkingapp-c2aed',
    storageBucket: 'parkingapp-c2aed.firebasestorage.app',
    iosBundleId: 'com.example.parkingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnWaueIWXMgJ5iAx8AEiFTh1kSg3jiFpk',
    appId: '1:859425192019:web:50623a4ecd54dd3701eea6',
    messagingSenderId: '859425192019',
    projectId: 'parkingapp-c2aed',
    authDomain: 'parkingapp-c2aed.firebaseapp.com',
    storageBucket: 'parkingapp-c2aed.firebasestorage.app',
    measurementId: 'G-WX9Z9102Y4',
  );
}
